version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: gql_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
    driver: local
# Running
# docker compose up -d
#
# Stop
# docker compose down
#
# Akses di bash container
# docker exec -it b9afd872ce30 mongosh -u root -p example
#
# Akses di mongodb kompas
# mongodb://root:example@localhost:27017

